POST   http://127.0.0.1:5001/nutra-nourish/us-central1/addSingleData
Content-Type: application/json

{
"data":      {
            "price": 35,
            "link": "Link not provided",
            "description": "Mix 10 grams (approximately one scoop) in water per day",
            "product_name": "Essential green",
            "key": "recommendation41",
            "properties": {
              "Gluten_free": true,
              "non_vegetarian": false,
              "vegan": true,
              "Dairy_free": true
            }
          },
         
"collectionName": "recommendations"
}	
